working_directory ="None"

[window]
dimensions = { columns = 80, lines=25 }
position = "None"
padding = { x = 6, y =6 }
decorations = "Full"
opacity = 0.9
blur = false
startup_mode = "Windowed"
title = "terminal"
dynamic_title =true
decorations_theme_variant = "None"
resize_increments = false

[scrolling]
history =10000
multiplier = 1

[env]

[font]

[colors]
cursor ={ text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor ={ text = "CellBackground", cursor = "#ac4242" }

[keyboard]
bindings = 	[{key ="Return", mods = "Control", action= "SpawnNewInstance"}
		,{key ="Escape", mods = "Alt", action ="ToggleViMode"}
		,
]
