#doc:https://alacritty.org/config-alacritty.html
import=[]
working_directory ="None"
live_config_reload = true

[window]
dimensions = { columns = 80, lines=25 }
position = "None"
padding = { x = 6, y =6 }
decorations = "Full"
opacity = 0.9
blur = false
startup_mode = "Windowed"
title = "terminal"
dynamic_title =true
decorations_theme_variant = "None"
resize_increments = false

[scrolling]
history =10000
multiplier = 1

[selection]
save_to_clipboard=true

[font]

[colors]
cursor ={ text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor ={ text = "CellBackground", cursor = "#ac4242" }

[keyboard]
bindings = 	[{key ="Return",	mods = "Alt", action= "SpawnNewInstance"}
		,{key ="Escape",	mods = "Alt", action ="ToggleViMode"}
		,{key ="q",		mods = "Alt", action ="Quit"}
		,

]

